const MyCardList = [
  {
    cardNumber: "1",
    cvc: "123",
    performanceOk: true,
    cardLimit: 100000,
    charges: 50000,
    benefitUsage: 10000,
    cardInfo: {
      cardName: "신한카드 Mr.Life",
      companyName: "신한카드",
      benefitTotalLimit: null,
      cardType: "신용",
      annualFee: 15000,
      annualFeeForeign: 0,
      performance: 500000,
      imageUrl: "/assets/image/cards/신용카드이미지/1_신한카드_Mr.Life.png",
      benefits: [
        {
          categoryName: "주거·통신",
          benefitDesc: "월납요금(공과금) 10% 할인서비스",
          categoryType: "생활",
          benefitType: "할인",
          benefitValue: 10,
          benefitPoint: 0,
        },
        {
          categoryName: "마트·편의점",
          benefitDesc: "편의점 10% 할인",
          categoryType: "쇼핑",
          benefitType: "할인",
          benefitValue: 10,
          benefitPoint: 0,
        },
        {
          categoryName: "의료",
          benefitDesc: "병원/약국업종 10% 할인",
          categoryType: "생활",
          benefitType: "할인",
          benefitValue: 10,
          benefitPoint: 0,
        },
        {
          categoryName: "생활",
          benefitDesc: "세탁소 업종 10% 할인",
          categoryType: "생활",
          benefitType: "할인",
          benefitValue: 10,
          benefitPoint: 0,
        },
        {
          categoryName: "쇼핑",
          benefitDesc: "온라인 쇼핑 10% 할인",
          categoryType: "쇼핑",
          benefitType: "할인",
          benefitValue: 10,
          benefitPoint: 0,
        },
        {
          categoryName: "교통",
          benefitDesc: "택시 10% 할인",
          categoryType: "교통",
          benefitType: "할인",
          benefitValue: 10,
          benefitPoint: 0,
        },
        {
          categoryName: "식비",
          benefitDesc: "식음료 10% 할인",
          categoryType: "식비",
          benefitType: "할인",
          benefitValue: 10,
          benefitPoint: 0,
        },
        {
          categoryName: "마트·편의점",
          benefitDesc: "3대 마트 10% 할인",
          categoryType: "쇼핑",
          benefitType: "할인",
          benefitValue: 10,
          benefitPoint: 0,
        },
        {
          categoryName: "자동차",
          benefitDesc: "4대 정유사 리터당 60원 할인",
          categoryType: "자동차",
          benefitType: "할인",
          benefitValue: 60,
          benefitPoint: 0,
        },
        {
          categoryName: "쇼핑",
          benefitDesc: "인테이크몰 20% 할인",
          categoryType: "쇼핑",
          benefitType: "할인",
          benefitValue: 20,
          benefitPoint: 0,
        },
      ],
    },
  },
  {
    cardNumber: "2",
    cvc: "456",
    performanceOk: false,
    cardLimit: 100000,
    charges: 0,
    benefitUsage: 0,
    cardInfo: {
      cardName: "삼성카드 & MILEAGE PLATINUM (스카이패스)",
      companyName: "삼성카드",
      benefitTotalLimit: null,
      cardType: "신용",
      annualFee: 47000,
      annualFeeForeign: 0,
      performance: 0,
      imageUrl:
        "/assets/image/cards/신용카드이미지/2_삼성카드_&_MILEAGE_PLATINUM_(스카이패스).png",
      benefits: [
        {
          categoryName: "항공·여행",
          benefitDesc: "모든 가맹점 이용금액 1,000원당 1마일리지 기본적립",
          categoryType: "여행",
          benefitType: "적립",
          benefitValue: 1,
          benefitPoint: 0,
        },
        {
          categoryName: "쇼핑",
          benefitDesc: "백화점 이용금액 1,000원당 2마일리지 특별적립",
          categoryType: "쇼핑",
          benefitType: "적립",
          benefitValue: 2,
          benefitPoint: 0,
        },
        {
          categoryName: "자동차",
          benefitDesc: "주유 이용금액 1,000원당 2마일리지 특별적립",
          categoryType: "자동차",
          benefitType: "적립",
          benefitValue: 2,
          benefitPoint: 0,
        },
        {
          categoryName: "카페",
          benefitDesc: "커피 이용금액 1,000원당 2마일리지 특별적립",
          categoryType: "식비",
          benefitType: "적립",
          benefitValue: 2,
          benefitPoint: 0,
        },
        {
          categoryName: "마트·편의점",
          benefitDesc: "편의점 이용금액 1,000원당 2마일리지 특별적립",
          categoryType: "쇼핑",
          benefitType: "적립",
          benefitValue: 2,
          benefitPoint: 0,
        },
        {
          categoryName: "교통",
          benefitDesc: "택시 이용금액 1,000원당 2마일리지 특별적립",
          categoryType: "교통",
          benefitType: "적립",
          benefitValue: 2,
          benefitPoint: 0,
        },
      ],
    },
  },
  {
    cardNumber: "3",
    cvc: "789",
    performanceOk: true,
    cardLimit: 100000,
    charges: 40000,
    benefitUsage: 5000,
    cardInfo: {
      cardName: "KB국민 My WE:SH 카드",
      companyName: "KB국민카드",
      benefitTotalLimit: null,
      cardType: "신용",
      annualFee: 15000,
      annualFeeForeign: 0,
      performance: 400000,
      imageUrl: "/assets/image/cards/신용카드이미지/3_KB국민_My_WE_SH_카드.png",
      benefits: [
        {
          categoryName: "간편결제",
          benefitDesc: "KB Pay 10% 할인",
          categoryType: "결제",
          benefitType: "할인",
          benefitValue: 10,
          benefitPoint: 0,
        },
        {
          categoryName: "마트·편의점",
          benefitDesc: "편의점 10% 할인",
          categoryType: "쇼핑",
          benefitType: "할인",
          benefitValue: 10,
          benefitPoint: 0,
        },
        {
          categoryName: "식비",
          benefitDesc: "음식점 10% 할인",
          categoryType: "식비",
          benefitType: "할인",
          benefitValue: 10,
          benefitPoint: 0,
        },
        {
          categoryName: "주거·통신",
          benefitDesc: "이동통신요금 10% 할인",
          categoryType: "통신",
          benefitType: "할인",
          benefitValue: 10,
          benefitPoint: 0,
        },
        {
          categoryName: "생활",
          benefitDesc: "OTT 30% 할인",
          categoryType: "생활",
          benefitType: "할인",
          benefitValue: 30,
          benefitPoint: 0,
        },
      ],
    },
  },
];
const RecommendedCardList = [
  {
    cardNumber: "R1",
    cvc: "000",
    performanceOk: false,
    cardLimit: 100000,
    charges: 0,
    benefitUsage: 0,
    cardInfo: {
      cardName: "현대카드 Summit",
      companyName: "현대카드",
      benefitTotalLimit: null,
      cardType: "신용",
      annualFee: 200000,
      annualFeeForeign: 0,
      performance: 500000,
      imageUrl: "",
      benefits: [
        {
          categoryName: "all",
          benefitDesc: "적립한도 제한 없는 1.5% M포인트 적립",
          categoryType: "기타",
          benefitType: "적립",
          benefitValue: 1.5,
          benefitPoint: 0,
        },
        {
          categoryName: "교육",
          benefitDesc: "[추가 혜택] 학원/유치원 업종 5% M포인트 적립",
          categoryType: "교육",
          benefitType: "적립",
          benefitValue: 5,
          benefitPoint: 0,
        },
        {
          categoryName: "의료",
          benefitDesc: "[추가 혜택] 병원/약국 업종 5% M포인트 적립",
          categoryType: "의료",
          benefitType: "적립",
          benefitValue: 5,
          benefitPoint: 0,
        },
        {
          categoryName: "항공·여행",
          benefitDesc: "[추가 혜택] 국내 항공사/여행사 업종 5% M포인트 적립",
          categoryType: "항공·여행",
          benefitType: "적립",
          benefitValue: 5,
          benefitPoint: 0,
        },
        {
          categoryName: "숙박",
          benefitDesc: "[추가 혜택] 특급호텔 업종 5% M포인트 적립",
          categoryType: "숙박",
          benefitType: "적립",
          benefitValue: 5,
          benefitPoint: 0,
        },
      ],
    },
  },
  {
    cardNumber: "R2",
    cvc: "000",
    performanceOk: false,
    cardLimit: 100000,
    charges: 0,
    benefitUsage: 0,
    cardInfo: {
      cardName: "LOCA 365 카드",
      companyName: "LOCA",
      benefitTotalLimit: null,
      cardType: "신용",
      annualFee: 20000,
      annualFeeForeign: 0,
      performance: 500000,
      imageUrl: "",
      benefits: [
        {
          categoryName: "주거·통신",
          benefitDesc: "[생활업종] 아파트관리비 10% 할인",
          categoryType: "주거·통신",
          benefitType: "할인",
          benefitValue: 10,
          benefitPoint: 0,
        },
        {
          categoryName: "주거·통신",
          benefitDesc: "[생활업종] 공과금(도시가스비, 전기료) 10% 할인",
          categoryType: "주거·통신",
          benefitType: "할인",
          benefitValue: 10,
          benefitPoint: 0,
        },
        {
          categoryName: "교통",
          benefitDesc: "[생활업종] 대중교통 10% 할인",
          categoryType: "교통",
          benefitType: "할인",
          benefitValue: 10,
          benefitPoint: 0,
        },
        {
          categoryName: "주거·통신",
          benefitDesc: "[생활업종] SKT, KT, LG U+ 10% 할인",
          categoryType: "주거·통신",
          benefitType: "할인",
          benefitValue: 10,
          benefitPoint: 0,
        },
        {
          categoryName: "식비",
          benefitDesc: "[생활업종] 배달의 민족, 요기요, 쿠팡이츠 10% 할인",
          categoryType: "식비",
          benefitType: "할인",
          benefitValue: 10,
          benefitPoint: 0,
        },
        {
          categoryName: "보험",
          benefitDesc: "[생활업종] 생명보험, 손해보험 10% 할인",
          categoryType: "보험",
          benefitType: "할인",
          benefitValue: 10,
          benefitPoint: 0,
        },
        {
          categoryName: "교육",
          benefitDesc: "[생활업종] 학습지 10% 할인",
          categoryType: "교육",
          benefitType: "할인",
          benefitValue: 10,
          benefitPoint: 0,
        },
        {
          categoryName: "생활",
          benefitDesc:
            "[생활업종] 넷플릭스, 유튜브, 왓챠, 멜론, 지니뮤직, 디즈니 플러스 1,500원 할인",
          categoryType: "생활",
          benefitType: "할인",
          benefitValue: 1500,
          benefitPoint: 0,
        },
      ],
    },
  },
  {
    cardNumber: "R3",
    cvc: "000",
    performanceOk: false,
    cardLimit: 100000,
    charges: 0,
    benefitUsage: 0,
    cardInfo: {
      cardName: "현대카드Z family Edition2",
      companyName: "현대카드",
      benefitTotalLimit: null,
      cardType: "신용",
      annualFee: 20000,
      annualFeeForeign: 0,
      performance: 500000,
      imageUrl: "",
      benefits: [
        {
          categoryName: "쇼핑",
          benefitDesc: "온라인 쇼핑몰 10% 청구 할인",
          categoryType: "쇼핑",
          benefitType: "청구 할인",
          benefitValue: 10,
          benefitPoint: 0,
        },
        {
          categoryName: "의료",
          benefitDesc: "병원・약국 10% 청구 할인",
          categoryType: "의료",
          benefitType: "청구 할인",
          benefitValue: 10,
          benefitPoint: 0,
        },
        {
          categoryName: "교육",
          benefitDesc: "학원 10% 청구 할인",
          categoryType: "교육",
          benefitType: "청구 할인",
          benefitValue: 10,
          benefitPoint: 0,
        },
        {
          categoryName: "자동차",
          benefitDesc: "주유 10% 청구 할인",
          categoryType: "자동차",
          benefitType: "청구 할인",
          benefitValue: 10,
          benefitPoint: 0,
        },
        {
          categoryName: "주거·통신",
          benefitDesc: "생활 요금 정기 결제 10% 청구 할인",
          categoryType: "주거·통신",
          benefitType: "청구 할인",
          benefitValue: 10,
          benefitPoint: 0,
        },
      ],
    },
  },
];
export { RecommendedCardList, MyCardList };
