spring:
  application:
    name: store

  config:
    import: "configserver:${SPRING_CLOUD_CONFIG_URI:http://localhost:8888}"

  cloud:
    config:
      name: store
      profile: ${SPRING_PROFILES_ACTIVE:local}