spring:
  application:
    name: gateway
  main:
    allow-bean-definition-overriding: true

  config:
    import: "configserver:${SPRING_CLOUD_CONFIG_URI:http://localhost:8888}"

  cloud:
    config:
      name: gateway
      profile: ${SPRING_PROFILES_ACTIVE:local}